version: "3"
services: 
    java_app:
        container_name: java
        restart: always
        ports: 
            - "8082:8082"
        build: 
            context: .
            dockerfile: Dockerfile